Ahrjarrett@optimize tagged enum
Effect-TS/effect pull request #1521
Opened 2023-10-14 20:46 UTC by ahrjarrett

Closes https://github.com/Effect-TS/effect/issues/1497

Note: I was not intending to work on this issue -- originally I was actually contributing a minor type-level performance improvement to TaggedEnum, and when I went to open the PR, I checked to see if there were any related issues or pull requests, and saw #1497 (and happened to know how to make that work).

Happy to make any requested adjustments, and I apologize if any of the names aren't clear -- I wrote this rather quickly, and figured better to get feedback before spending too long on it :)

2023-10-14 20:59 UTC, ahrjarrett commented
Re-reading the changes, I'm not particularly happy with the name `CheckUntagged`. Maybe it makes more sense to just it `Untagged`?

2023-10-15 01:09 UTC, ahrjarrett commented on src/Data.ts
> +  ? `It looks like you're trying to create a tagged enum, but one or more of its members already have a \`_tag\` property.`
```suggestion
  ? `It looks like you're trying to create a tagged enum, but one or more of its members already has a \`_tag\` property.`
```

2023-10-15 01:09 UTC, ahrjarrett commented on src/Data.ts
> +  A extends Record<string, Record<string, any>> & CheckUntagged<_>,
```suggestion
  A extends Record<string, Record<string, any>> & Untagged<_>,
```

2023-10-15 01:10 UTC, ahrjarrett commented on src/Data.ts
> +type CheckUntagged<_ extends { isTagged: any }>
```suggestion
type Untagged<_ extends { isTagged: any }>
```

2023-10-15 05:52 UTC, tim-smart requested changes
Almost there thanks! Definitely an interesting concoction of types :)

I wonder if it can be simplified at all? My only concern is from a maintainability point of view - in a few months time I can imagine myself staring at it for a few minutes before figuring out what is going on.

2023-10-15 05:52 UTC, tim-smart commented on src/Data.ts
> +/** @internal */
Will need to remove the internal comments otherwise the types will be stripped away.

2023-10-15 07:03 UTC, ahrjarrett commented
> Almost there thanks! Definitely an interesting concoction of types :)
> 
> I wonder if it can be simplified at all? My only concern is from a maintainability point of view - in a few months time I can imagine myself staring at it for a few minutes before figuring out what is going on.

Fair enough, I can take another stab at it.

2023-10-15 07:04 UTC, ahrjarrett commented on src/Data.ts
> +/** @internal */
```suggestion
```

2023-10-15 14:48 UTC, gcanti commented
@ahrjarrett what about

```ts
export type TaggedEnum<A extends Record<string, Record<string, any>> & UntaggedChildren<A>> = {
  readonly [Tag in keyof A]: Data<
    { readonly [K in keyof A[Tag] | "_tag"]: K extends "_tag" ? Tag : A[Tag][K] }
  >
}[keyof A]

type ChildrenAreTagged<A> = { [K in keyof A]: "_tag" extends keyof A[K] ? true : false }[keyof A]

type UntaggedChildren<A> = ChildrenAreTagged<A> extends true
  ? "It looks like you're trying to create a tagged enum, but one or more of its members already has a `_tag` property."
  : unknown
```

type-level tests to add in `/dtslint/Data.ts`

```ts
import * as Data from 'effect/Data'

type HttpError = Data.TaggedEnum<{
  BadRequest: { status: 400, a: string }
  NotFound: { status: 404, b: number }
}>
// $ExpectType Data<{ readonly a: string; readonly status: 400; readonly _tag: "BadRequest"; }>
type BadRequest = Extract<HttpError, { _tag: 'BadRequest' }>
// $ExpectType Data<{ readonly b: number; readonly status: 404; readonly _tag: "NotFound"; }>
type NotFound = Extract<HttpError, { _tag: 'NotFound' }>

// @ts-expect-error
type Err = Data.TaggedEnum<{
  BadRequest: { _tag: 'BadRequest' }
}>
```

2023-10-16 01:59 UTC, tim-smart approved these changes

2023-10-16 02:15 UTC, merged