improved Duration.toString
Effect-TS/effect pull request #1703
Opened 2023-11-24 21:23 UTC by jessekelly881

2023-11-27 07:28 UTC, gcanti commented on src/Duration.ts
> -    return toString(this.toJSON())
IMO showing a stringified JSON is more a default when we can't come up with sth better than a rule.
A recent example is BigDecimal (I guess this PR is along the lines of that data type), but I agree that `format` would be a better name than `toString` (also in the BigDecimal module)

2023-11-28 07:55 UTC, tim-smart commented on src/Duration.ts
> -    return toString(this.toJSON())
Maybe the .toString should be `Duration(150ms)` etc.

2023-11-28 22:42 UTC, tim-smart requested changes

2023-11-28 22:42 UTC, tim-smart commented on src/Duration.ts
> +    return format(this)
I thing only toString should add the `Duration()` notation.

2023-11-28 22:42 UTC, tim-smart commented on src/Duration.ts
> +    return "Duration(Infinity)"
Remove `Duration()` here, as then it makes `format` more general purpose.

2023-11-29 00:37 UTC, tim-smart requested changes

2023-11-29 00:37 UTC, tim-smart commented on src/Duration.ts
> + * Duration.format(Duration.millis(1000)) // "Duration(1s)"
Just need to update the example :)

2023-11-29 00:43 UTC, jessekelly881 commented on src/Duration.ts
> + * Duration.format(Duration.millis(1000)) // "Duration(1s)"
oops

2023-11-29 00:46 UTC, tim-smart approved these changes

2023-11-29 00:46 UTC, merged