`RateLimiter` : Sub-constructor to customize `cost` + Rate Limiter composition tests
Effect-TS/effect pull request #2090
Opened 2024-02-10 06:37 UTC by hsubra89

## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

This patch updates the `RateLimiter` module to include another constructor which includes a sub-constructor which allows us to specify a cost while maintaining composability with other `RateLimiter` instances. This enables the use of this module to rate limit for the following cases : 
- Accessing resources with an "API Credit" limits over a time window.

- With composition, accounting for multiple "credit" limits. ( eg: [Github API](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits) ) 

- Accounting for different "costs" per api per provider within a single credit limit. 
  - Many providers have different API costs for different endpoints within their ecosystem.

**NOTE** : I'm not really particularly happy with the naming of the model and constructor.

2024-02-10 18:48 UTC, IMax153 commented
@hsubra89 - apologies for the back-and-forth with the `RateLimiter`. We discovered the updated implementation was utilizing the fixed-window algorithm for token replenishment instead of the token-bucket algorithm. 

The fix is in #2097. Please update this MR once the bugfix is merged.

2024-02-10 21:09 UTC, hsubra89 commented
> @hsubra89 - apologies for the back-and-forth with the `RateLimiter`. We discovered the updated implementation was utilizing the fixed-window algorithm for token replenishment instead of the token-bucket algorithm. 
> 
> 
> 
> The fix is in #2097. Please update this MR once the bugfix is merged.

No problem. I did notice that when the implementation was changed but didn't look into it too deeply.

2024-02-11 07:51 UTC, hsubra89 commented
Depends on #2097

2024-02-11 20:36 UTC, tim-smart requested changes
I think we should merge this first, as the other PR will need to add more tests to make sure `cost` is well supported.

2024-02-11 20:36 UTC, tim-smart commented on packages/effect/src/internal/rateLimiter.ts
> +export const makeWithCost = (limit: number, window: DurationInput): Effect.Effect<
This can be removed now?

2024-02-11 20:36 UTC, tim-smart commented on packages/effect/src/internal/rateLimiter.ts
> +export const withCost = (cost: number) => Effect.locallyWith(defaultCost, () => cost)
```suggestion
export const withCost = (cost: number) => Effect.locally(defaultCost, cost)
```

2024-02-11 20:42 UTC, IMax153 requested changes

2024-02-11 21:22 UTC, hsubra89 commented on packages/effect/src/internal/rateLimiter.ts
> +export const makeWithCost = (limit: number, window: DurationInput): Effect.Effect<
Sorry, that was dumb. Removed.

2024-02-11 21:22 UTC, hsubra89 commented on packages/effect/src/internal/rateLimiter.ts
> +const defaultCost = globalValue(
Done.

2024-02-11 21:26 UTC, tim-smart approved these changes

2024-02-11 21:31 UTC, merged