Chunk difference methods
Effect-TS/effect pull request #2658
Opened 2024-04-30 06:39 UTC by RareBodhi

## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Adds a set of `difference` operations directly on the Chunk method. I also have a zipped stream use case, and can imagine other use cases getting chunk values from Map's etc. where a `differenceOption` function would be useful.

My initial implementation enforced the first "comparator" Chunk to be a `Option<Chunk<A>>` however I opted to separate the methods.

Please let me know if this is in accordance with the envisaged interface, or if you'd rather not split the option handling. For now my use case has less boilerplate when the first Chunk is Optional.

2024-04-30 07:49 UTC, fubhy requested changes

2024-04-30 07:49 UTC, fubhy commented on packages/effect/src/Chunk.ts
> +)
I'm always on the fence when it comes to adding additional permutations / combinations like these that can be easily composed in userland. It always raises the question "where do we stop?". E.g. here we could also add a variant for `Either` and `Exit`, etc.

Even though that is also true for the other two, I can see the value in those, but I would leave this one out.

2024-04-30 23:38 UTC, tim-smart requested changes
Could you add a minor changeset?

2024-04-30 23:38 UTC, tim-smart commented on packages/effect/src/Chunk.ts
> + * @since 2.0.0
```suggestion
 * @since 3.2.0
```

2024-05-01 04:30 UTC, tim-smart commented
I think you forgot to add the file 😅

2024-05-13 05:06 UTC, merged