Introduce `Hidden<T>` module
Effect-TS/effect pull request #2856
Opened 2024-05-26 12:46 UTC by KhraksMamtsov

## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

- Introduce `Hidden<T>` module - as mentioned here https://github.com/Effect-TS/effect/pull/2810
- `Secret extends Hidden<string>`
- Have added two related schemas 
- Have added tests
- Have Changed `Secret` usage on `Hidden<string>` in packages with version `0.*.*`

## Related

- Related Issue #
- Closes #

2024-05-27 09:31 UTC, mikearnaldi commented
Accessing a value after wipe should probably throw instead of returning undefined

2024-05-27 10:48 UTC, mikearnaldi commented
Wondering if we should go for Hidden or Redacted as a name, I sort of like Redacted more because it is in line with what's shown in logs and has precedents in other languages like https://github.com/polentino/redacted

2024-05-27 10:56 UTC, KhraksMamtsov commented
Understood, I will rename it in the near future

2024-05-28 23:41 UTC, tim-smart requested changes

2024-05-29 06:42 UTC, mikearnaldi commented
Re failing test this is due to missing re-export from index, you can add that by running `pnpm codegen`

2024-05-29 07:03 UTC, KhraksMamtsov commented on packages/effect/src/internal/redacted.ts
> +  Object.defineProperty(redacted, "toString", {
Done

2024-05-29 07:36 UTC, KhraksMamtsov commented on packages/effect/src/Redacted.ts
> +export interface Redacted<out A> extends Redacted.Variance<A>, Equal.Equal, Pipeable {
I agree - I corrected it

2024-05-29 07:40 UTC, KhraksMamtsov commented on packages/cli/src/Args.ts
> +export const hidden: (config?: Args.BaseArgsConfig) => Args<Redacted<string>> = InternalArgs.hidden
Ok, then I will keep `Secret`&`SecretFromSelf` schemas for `@effect/schema` as well

2024-05-29 09:44 UTC, KhraksMamtsov commented on .changeset/slow-paws-check.md
> +Added two related schemas `Redacted` and `RedactedFromSelf`
done

2024-05-29 14:42 UTC, KhraksMamtsov commented
It seems that I have corrected all the comments,
please point out the flaws if something is wrong

2024-05-29 22:21 UTC, tim-smart approved these changes

2024-05-29 22:35 UTC, merged