vitest: add basic docs
Effect-TS/effect pull request #2868
Opened 2024-05-28 15:50 UTC by gcanti

2024-05-28 20:50 UTC, IMax153 requested changes

2024-05-28 20:50 UTC, IMax153 commented on packages/vitest/README.md
> +Welcome to your guide on testing Effect applications using `vitest` and the `@effect/vitest` package. This guide is designed to help beginners efficiently set up their testing environment and create
This sounds a bit GPT-ish 😅 - maybe the following?

```suggestion
Welcome to your guide on testing Effect applications using `vitest` and the `@effect/vitest` package! `@effect/vitest` is designed to help simplify running Effect-based tests through `vitest`. 

In the guide below, we will first start by setting up the required dependencies. Then, we will dive into a few examples of how to use `@effect/vitest` to create some Effect-based test cases.
```

2024-05-28 20:50 UTC, IMax153 commented on packages/vitest/README.md
> +Next, install the `@effect/vitest` package. This package integrates the Effect framework with Vitest for enhanced testing capabilities.
```suggestion
Next, install the `@effect/vitest` package which facilitates running Effect-based tests through `vitest`.
```

2024-05-28 20:50 UTC, IMax153 commented on packages/vitest/README.md
> +When using `it.effect`, the `TestContext` is automatically injected, simplifying test setup and execution.
```suggestion
When using `it.effect`, the `TestContext` is automatically injected, which allows tests to have access to services designed to facilitate testing (such as the [`TestClock`](#using-the-testclock)).
```

2024-05-28 20:50 UTC, IMax153 commented on packages/vitest/README.md
> +To demonstrate, let's create a test for a function that divides two numbers but fails if the divisor is zero:
```suggestion
Let's create a test for a function that divides two numbers but fails if the divisor is zero:
```

2024-05-28 20:50 UTC, IMax153 commented on packages/vitest/README.md
> +The `TestClock` is seamlessly integrated into your tests when you use `it.effect`, making it easy to simulate the passage of time. If you want to execute your tests in the real, live Effect environme
```suggestion
When using `it.effect`, a `TestContext` is provided to your program which provides access to several services designed to facilitate testing. One such service is the `[TestClock`](https://effect.website/docs/guides/testing/testclock) which is designed to simulate the passage of time. 

**Note**: To utilize the default, non-testing services in your tests you can use `it.live`.
```

2024-05-29 08:55 UTC, vecerek commented on packages/vitest/README.md
> +    yield* TestQlock.adjust("1000 millis")
```suggestion
    yield* TestClock.adjust("1000 millis")
```

2024-05-29 14:25 UTC, IMax153 approved these changes
LGTM 👍 Thanks @gcanti !

2024-05-29 15:04 UTC, merged