Add `Effect.liftPredicate`
Effect-TS/effect pull request #2956
Opened 2024-06-08 13:43 UTC by LaureRC

## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Add `Effect.liftPredicate` (similar to recently merged `Either.liftPredicate`) 

## Related

N/A

2024-06-12 01:15 UTC, tim-smart commented
I think the Effect.filter* apis are enough:

```ts
Effect.succeed(0).pipe(
  Effect.filterOrFail(...)
)
```

I'll let someone else weigh in before we decide to continue / close this PR.

2024-06-12 17:40 UTC, LaureRC commented
Thank you for your reviews!

> I think the Effect.filter* apis are enough:

I understand your point, I thought it would be more convenient to directly have this `liftPredicate`, rather than have to wrap the initial value in an `Effect.succeed` to be able to use the `Effect.filter*` methods

> That's right, this is literally Either.liftPredicate typed differently:

Right, but then does that mean you don't recommend adding it for Effect? We can use `Either.liftPredicate` which is going to be released in the next minor anyway so I'm happy with that 🙂 but apparently some people do not use `Either` that much, so it could be convenient for them to not have to import (and know) about another module than `Effect`. I'm aware this is not a super strong argument though, so if you think that's not interesting enough I won't be mad if we close this subject 😄

2024-06-12 18:02 UTC, gcanti commented
Actually, I'm not sure they are *literally* the same,`Effect.succeed`/`Effect.fail` and `Either.right`/`Either.left` return different values.

2024-06-17 07:47 UTC, LaureRC commented
> Actually, I'm not sure they are literally the same,Effect.succeed/Effect.fail and Either.right/Either.left return different values.

Indeed, in some cases I identified in my current project, it does not change much to use the Either one. As I said before, I was pushing a little bit for this `Effect.liftPredicate` as I still think it could have value to have this method in both `Either` and `Effect` modules, to avoid having to "switch context" and use the `Either` module if not really needed. 
So I'll reopen the PR as I still think it could be useful, but don't hesitate to push back on it if you disagree 🙂 (as I didn't get an explicit no-go for now I'll insist a little bit more 😄)

2024-06-19 21:33 UTC, tim-smart requested changes

2024-06-19 21:33 UTC, tim-smart commented on packages/effect/src/Effect.ts
> +} = dual(
If you can move the implementation into `internal/core-effect.ts`, to be consistent with the rest of the apis.

2024-06-19 21:33 UTC, tim-smart commented on packages/effect/src/Effect.ts
> +    predicate(a) ? succeed(a) : fail(orFailWith(a))
This needs to be wrapped in `Effect.suspend`, in case the predicate throws an error.

2024-06-20 01:14 UTC, tim-smart commented
I'll make the changes now to get this into the next minor release.

2024-06-20 01:24 UTC, tim-smart approved these changes

2024-06-20 01:36 UTC, merged

2024-06-21 18:24 UTC, LaureRC commented
> I'll make the changes now to get this into the next minor release.

Thank you for handling this! I'm glad to see this released 😊