Support unification for `Micro` module
Effect-TS/effect pull request #3078
Opened 2024-06-24 17:13 UTC by KhraksMamtsov

## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related

- Related Issue #
- Closes #

2024-06-24 22:19 UTC, tim-smart requested changes

2024-06-24 22:19 UTC, tim-smart commented on packages/effect/src/Micro.ts
> + * @since 2.0.0
```suggestion
 * @since 3.4.3
```

2024-06-24 22:19 UTC, tim-smart commented on packages/effect/src/Micro.ts
> + * @since 2.0.0
```suggestion
 * @since 3.4.3
```

2024-06-24 22:19 UTC, tim-smart commented on .changeset/rare-cameras-explain.md
> +"effect": minor
```suggestion
"effect": patch
```

2024-06-25 09:00 UTC, KhraksMamtsov commented
Don't know how to change target brunch(
Bot has changed it from the `main`

2024-06-25 09:02 UTC, mikearnaldi commented
> Don't know how to change target brunch( Bot has changed it from the `main`

Done, you need to hit Edit on the PR title, it's an odd ux imho

2024-06-25 22:23 UTC, tim-smart approved these changes

2024-06-25 22:26 UTC, merged