feat(Stream): race
Effect-TS/effect pull request #3305
Opened 2024-07-19 05:39 UTC by dilame

2024-07-26 01:21 UTC, tim-smart commented
/rebase

2024-07-26 01:24 UTC, tim-smart requested changes

2024-07-26 01:24 UTC, tim-smart commented on packages/effect/src/Stream.ts
> +    stream2: Stream<A2, E2, R2>
To align with the other apis:

```suggestion
    that: Stream<A2, E2, R2>
  ): <A1, E1, R1>(self: Stream<A1, E1, R1>) => Stream<A1 | A2, E1 | E2, R1 | R2>
  <A1, E1, R1, A2, E2, R2>(
    self: Stream<A1, E1, R1>,
    that: Stream<A2, E2, R2>
```

2024-08-22 14:12 UTC, dilame commented
@tim-smart i applied the changes from the review

2024-08-22 21:09 UTC, tim-smart requested changes

2024-08-22 21:09 UTC, tim-smart commented on packages/effect/src/Stream.ts
> + * @since 3.6.0
```suggestion
 * @since 3.7.0
```

2024-08-23 00:01 UTC, tim-smart approved these changes

2024-08-23 00:17 UTC, merged