Fix `Cache<_, Value, _>` type parameter variance (covariant -> invariant)
Effect-TS/effect pull request #3404
Opened 2024-08-03 08:59 UTC by KhraksMamtsov

## Type

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related

- Related Issue #
- Closes #

2024-08-05 20:28 UTC, mikearnaldi commented
just changing `out` to `in out` doesn't actually affect variance when compared structurally, we should use the `Variance` trick we use in `Effect` and on the other types to force a specific variance

2024-08-06 14:00 UTC, KhraksMamtsov commented
Done.
I used the `Cache.Variance` type for the regular `Cache`, and for `ConsumerCache` - `Cache.ConsumerVariance`.
And now `CacheImpl` contains both `Variance` symbols.
I was looking at `Queue` which implements `Enqueue` + `Dequeue`

2024-08-07 21:59 UTC, tim-smart requested changes

2024-08-07 21:59 UTC, tim-smart commented on packages/effect/src/Cache.ts
> + * @since 2.0.0
```suggestion
 * @since 3.6.2
```

2024-08-08 07:08 UTC, KhraksMamtsov commented on packages/effect/src/Cache.ts
> + * @since 2.0.0
Done

2024-08-12 01:03 UTC, tim-smart requested changes

2024-08-12 01:03 UTC, tim-smart commented on packages/effect/src/Cache.ts
> + * @since 3.6.2
```suggestion
 * @since 3.6.4
```

2024-08-12 01:03 UTC, tim-smart commented on packages/effect/src/Cache.ts
> + * @since 3.6.2
```suggestion
 * @since 3.6.4
```

2024-08-12 01:03 UTC, tim-smart commented on packages/effect/src/Cache.ts
> +   * @since 3.6.2
```suggestion
   * @since 3.6.4
```

2024-08-12 01:09 UTC, tim-smart approved these changes

2024-08-12 01:18 UTC, merged