Introduced `RandomScheduler`
Effect-TS/effect pull request #3456
Opened 2024-08-14 13:24 UTC by KhraksMamtsov

## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related

- Related Issue #
- Closes #

2024-08-14 22:31 UTC, tim-smart requested changes

2024-08-14 22:31 UTC, tim-smart commented on .changeset/cyan-coats-peel.md
> +"effect": patch
```suggestion
"effect": minor
```

2024-08-14 22:31 UTC, tim-smart commented on packages/effect/src/Scheduler.ts
> + * @since 3.6.4
```suggestion
 * @since 3.7.0
```

2024-08-15 06:54 UTC, KhraksMamtsov commented on .changeset/cyan-coats-peel.md
> +"effect": patch
done

2024-08-15 06:54 UTC, KhraksMamtsov commented on packages/effect/src/Scheduler.ts
> + * @since 3.6.4
done

2024-08-15 07:10 UTC, mikearnaldi commented
Order of execution within the same priority is semantically important, introducing non determinism at that level may lead to very hard to debug issues and is unwarranted. I think if you want to introduce non-determinism you can do so by yielding to a random priority instead of processing with a random order

2024-08-15 08:42 UTC, KhraksMamtsov commented
```
[1,[a,b,c]]
[2,[d,e,f]]

[c-b-a, e-d-f] // respect priority but not order inside priority
[d-e-f, a-b-c] // respect order inside priority but no priority itself
```
in the first case, the semantics of priorities are preserved.
and in the second case, the priorities can simply be called a group of tasks.
Are you sure about this?

2024-08-17 12:44 UTC, mikearnaldi commented
```
I believe that usage RandomScheduler will highlight this kind of bugs.
And we shouldn't rely on execution order within one priority and use correct concurrent primitives correctly)
It is assumed that it will be used in testing
```

No, order of execution has to be guaranteed otherwise semantics are broken. That's a required invariant for Effect to work, we have to rely on order of execution.

2024-08-17 12:53 UTC, KhraksMamtsov commented
Ok, It's clear, thank you

2024-08-17 12:53 UTC, closed without merging

2024-08-17 13:20 UTC, KhraksMamtsov commented
> No, order of execution has to be guaranteed otherwise semantics are broken. That's a required invariant for Effect to work, we have to rely on order of execution. Both priority and order within priority.

I think it should be reflected somewhere in the documentation.

2024-08-17 13:26 UTC, KhraksMamtsov commented
Also I am glad that another bug was discovered and fixed during the development of this PR)

2024-08-17 13:28 UTC, mikearnaldi commented
Which bug? Re docs we can add it to the scheduler docs, it's fairly low level to make schedulers manually and there can be a degree of freedom e.g. one may decide to execute random within a specific priority that is not used elsewhere. Will try to find a good explainer

2024-08-17 13:49 UTC, KhraksMamtsov commented
@mikearnaldi 
https://discord.com/channels/795981131316985866/795983589644304396/1273026396779974807
https://github.com/Effect-TS/effect/pull/3452

2024-08-17 14:04 UTC, mikearnaldi commented
Ah yeah indeed