[effect] add Logger.withLeveledConsole
Effect-TS/effect pull request #3540
Opened 2024-09-03 06:19 UTC by Schniz

## Type

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

In browsers and different platforms, `console.error` renders differently than `console.info`. This helps to distinguish between different levels of logging. `Logger.withLeveledConsole` takes any logger and calls the respective `Console` method based on the log level. For instance, `Effect.logError` will call `Console.error` and `Effect.logInfo` will call `Console.info`.

To use it, you can replace the default logger with a `Logger.withLeveledConsole` logger:

```ts
import { Logger, Effect } from "effect"

const loggerLayer = Logger.withLeveledConsole(Logger.stringLogger)

Effect.gen(function* () {
  yield* Effect.logError("an error")
  yield* Effect.logInfo("an info")
}).pipe(Effect.provide(loggerLayer))
```

## Related

- Related Issue #
- Closes #

2024-09-03 11:34 UTC, datner commented
Honestly I think this should be the default even, great idea

2024-09-04 00:02 UTC, tim-smart requested changes

2024-09-04 00:02 UTC, tim-smart commented on packages/effect/src/internal/fiberRuntime.ts
> +    const levels: Partial<Record<LogLevel.LogLevel["_tag"], (v: unknown) => void>> = {
A `switch` would be better here, instead of creating an intermediary object for every log.

2024-09-13 00:54 UTC, tim-smart approved these changes

2024-09-13 00:59 UTC, tim-smart commented
/rebase

2024-09-13 01:00 UTC, merged